"""Data binding and number provenance.

`data/bindings.json` is the single source of truth for every number a
composition may show:

    {
      "values": {
        "co2_2025": {"value": "427.35", "unit": "ppm", "display": "427.35 ppm",
                     "source": "raw/co2_annmean_mlo.csv", "location": "line 111"}
      },
      "series": {
        "co2": {"file": "derived/co2_ppm_annual.csv", "x": "year", "y": "co2_ppm"}
      },
      "allow": ["2026"]          # literals that may appear although no value binds them
    }

`bind()` validates the bindings, hashes their files and writes `data.js`
(window.DATA). The composition takes numbers only from Studio.fmt() /
Studio.series() / Studio.counter(). `allowed_numbers()` + `number_tokens()`
power the QA "no orphan numbers" check.
"""
from __future__ import annotations

import csv
import json
import re
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any

from .util import StudioError, read_json, sha256_file

NUMBER = re.compile(r"(?<![\w.])[+\-−]?\d{1,3}(?:[,  ]\d{3})+(?:\.\d+)?%?|(?<![\w.])[+\-−]?\d+(?:\.\d+)?%?")
PERSIAN = str.maketrans("۰۱۲۳۴۵۶۷۸۹٠١٢٣٤٥٦٧٨٩٫٬", "01234567890123456789.,")


def _decimals(text: str) -> int:
    return len(text.split(".", 1)[1]) if "." in text else 0


def canonical(token: str) -> str | None:
    """Normalize a displayed number to a canonical decimal string ('−1,234.50' -> '-1234.50')."""
    t = token.translate(PERSIAN).replace("−", "-").replace(",", "").replace(" ", "").replace(" ", "").rstrip("%")
    t = t.lstrip("+")
    try:
        d = Decimal(t)
    except InvalidOperation:
        return None
    return format(d, "f")


def number_tokens(text: str) -> list[str]:
    return NUMBER.findall(text.translate(PERSIAN))


def _read_series(root: Path, spec: dict[str, Any], name: str) -> dict[str, Any]:
    path = (root / spec["file"]).resolve()
    if not path.is_file() or not path.is_relative_to(root.resolve()):
        raise StudioError(f"series {name}: {spec['file']} is missing or outside data/")
    with path.open(newline="", encoding="utf-8-sig") as fh:
        rows = list(csv.DictReader(fh))
    if not rows or spec["x"] not in rows[0] or spec["y"] not in rows[0]:
        raise StudioError(f"series {name}: columns {spec['x']}/{spec['y']} not in {spec['file']}")
    points = []
    for i, row in enumerate(rows, start=2):
        x, y = row[spec["x"]].strip(), row[spec["y"]].strip()
        if y == "" or canonical(y) is None:
            raise StudioError(f"series {name}: {spec['file']} line {i} has non-numeric {spec['y']}={y!r}; clean the table, do not guess")
        points.append({"x": x, "y": y})
    return {"points": points, "file": spec["file"], "sha256": sha256_file(path), "x": spec["x"], "y": spec["y"],
            "label": spec.get("label", name), "unit": spec.get("unit", "")}


def bind(project: str | Path) -> dict[str, Any]:
    project = Path(project)
    root = project / "data"
    spec = read_json(root / "bindings.json")
    values = {}
    for key, v in spec.get("values", {}).items():
        raw = str(v["value"])
        if canonical(raw) is None:
            raise StudioError(f"value {key}: '{raw}' is not a number")
        unit = v.get("unit", "")
        display = v.get("display") or (f"{raw} {unit}".strip())
        if raw.replace("-", "−") not in display and raw not in display and _fmt_grouped(raw) not in display:
            raise StudioError(f"value {key}: display '{display}' does not contain the value {raw}")
        src = v.get("source")
        if src and not (root / src).is_file():
            raise StudioError(f"value {key}: source file data/{src} is missing")
        prefix, suffix = _affixes(display, raw)
        values[key] = {"value": raw, "display": display, "unit": unit, "decimals": _decimals(raw), "prefix": prefix,
                       "suffix": suffix, "grouping": "," in display, "source": src, "location": v.get("location", "")}
    series = {name: _read_series(root, s, name) for name, s in spec.get("series", {}).items()}
    out = {"values": values, "series": series, "allow": [str(a) for a in spec.get("allow", [])],
           "bindings_sha256": sha256_file(root / "bindings.json")}
    (project / "data.js").write_text("// generated by `mstudio data bind` from data/bindings.json; do not edit\nwindow.DATA = "
                                     + json.dumps(out, ensure_ascii=False, indent=1) + ";\n", encoding="utf-8")
    return out


def _fmt_grouped(raw: str) -> str:
    whole, _, frac = raw.lstrip("+-").partition(".")
    grouped = f"{int(whole):,}"
    return ("-" if raw.startswith("-") else "") + grouped + (f".{frac}" if frac else "")


def _affixes(display: str, raw: str) -> tuple[str, str]:
    for form in (raw, raw.replace("-", "−"), _fmt_grouped(raw), _fmt_grouped(raw).replace("-", "−")):
        i = display.find(form)
        if i >= 0:
            return display[:i], display[i + len(form):]
    return "", ""


def load(project: str | Path) -> dict[str, Any] | None:
    js = Path(project) / "data.js"
    if not js.is_file():
        return None
    text = js.read_text(encoding="utf-8")
    start = text.find("{")
    if start < 0:
        return None
    body = text[start:].rstrip().rstrip(";")
    try:
        return json.loads(body)
    except json.JSONDecodeError:
        return None


def allowed_numbers(data: dict[str, Any] | None, extra_texts: list[str]) -> set[str]:
    """Canonical numbers that may legitimately appear on screen."""
    allowed: set[str] = set()
    if data:
        for v in data.get("values", {}).values():
            for tok in [v["value"], *number_tokens(v["display"])]:
                c = canonical(tok)
                if c is not None:
                    allowed.add(c)
        for s in data.get("series", {}).values():
            for p in s["points"]:
                for tok in (p["x"], p["y"]):
                    c = canonical(tok)
                    if c is not None:
                        allowed.add(c)
        for a in data.get("allow", []):
            for tok in number_tokens(a) or [a]:
                c = canonical(tok)
                if c is not None:
                    allowed.add(c)
    for text in extra_texts:
        for tok in number_tokens(text):
            c = canonical(tok)
            if c is not None:
                allowed.add(c)
    return allowed


def number_allowed(token: str, allowed: set[str]) -> bool:
    # "+1.29" canonicalizes to "1.29"; a dropped minus sign does not match (sign errors are data errors)
    c = canonical(token)
    return c is None or c in allowed
